### ISSUE TITLE
Cannot build on react-native@0.65.x, ScreenshotDetectionDelegate.kt: (25, 13): 'onChange' overrides nothing

### ISSUE THREAD

**Issue by retyui** [AzizAK/react-native-detector#22]
How reproduce:

```bash
npx react-native init Test
cd Test
yarn add react-native-detector
npx react-native run-android


# you will next error: 
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
e: /home/i/open-source/DetectScreenshot/node_modules/react-native-detector/android/src/main/java/com/reactnativedetector/ScreenshotDetectionDelegate.kt: (25, 13): 'onChange' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-detector:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (/home/i/open-source/DetectScreenshot/node_modules/execa/index.js:174:9)
    at /home/i/open-source/DetectScreenshot/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/home/i/open-source/DetectScreenshot/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/home/i/open-source/DetectScreenshot/node_modules/@react-native-community/cli/build/index.js:186:9)
```

**Comment by AzizAK** [comment]
I think this because of Android 10, there is some changes on the storage api

**Comment by retyui** [comment]
> i will fix it this week muscle

I've just created PR to fix it: https://github.com/AzizAK/react-native-detector/pull/24

**Comment by AzizAK** [comment]
Fixed by #24 , Thanks to @retyui
